### ISSUE TITLE
When I try to download the pretrained model, it takes me to a login page, where I need to register. The registration is not possible, all the in

### ISSUE THREAD

**Issue by shiva319** [Kali-Hac/SGE-LA#1]

**Comment by shiva319** [comment]
When I try to download the pretrained model, it takes me to a login page, where I need to register. The registration is not possible as all the instructions are in Mandarin . It would be super awesome on part of you guys to upload the pretrained models on an international cloud sharing site so that everyone could benefit from that.

**Comment by Kali-Hac** [comment]
I have uploaded them to Dubox, a free cloud software worldwide. 

Already preprocessed datasets (BIWI, IAS, KGBD)
Dubox Sharelink：https://pan.baidu.com/s/1oOvY2pHM7DFQWcwfVwu6Lw
Password：kle5

All three trained models
Dubox Sharelink：https://pan.baidu.com/s/1367Gy-Bk9ojOrXveqCcm0Q
Password：r1jp

**Comment by Kali-Hac** [comment]
> When I try to download the pretrained model, it takes me to a login page, where I need to register. The registration is not possible as all the instructions are in Mandarin . It would be super awesome on part of you guys to upload the pretrained models on an international cloud sharing site so that everyone could benefit from that.

I have uploaded them to Google Drive and Dubox, both of which are free cloud software worldwide.

Already preprocessed datasets (BIWI, IAS, KGBD)
1. Google Sharelink:  https://drive.google.com/drive/folders/1apjNcFvlUk9kqnqB1khI3k1HX_cNH46p?usp=sharing
2. Dubox Sharelink:  https://pan.baidu.com/s/1oOvY2pHM7DFQWcwfVwu6Lw
Password:  kle5

All three trained models
1. Google Sharelink:  https://drive.google.com/drive/folders/1I7eSd37ArGJt46ZfUSzXT0ciDvgW9m-K?usp=sharing
2. Dubox Sharelink:  https://pan.baidu.com/s/1367Gy-Bk9ojOrXveqCcm0Q
Password:  r1jp
